etc/lightdm/lightdm.conf.d/91*
usr/sbin/arctica-greeter-guest-account-script
usr/libexec/arctica-greeter/arctica-greeter-guest-session-auto.sh
usr/libexec/arctica-greeter/arctica-greeter-guest-session-setup.sh
usr/share/lightdm/lightdm.conf.d/50-arctica-greeter-guest-wrapper.conf
usr/share/arctica-greeter/guest-session/skel/.config/autostart/arctica-greeter-guest-session-startup.desktop
usr/share/man/man8/
