.TH ARCTICA-GREETER 8 "Mar 16, 2018"
.SH NAME
arctica-greeter-guest-account-script \- Create temp user for an Arctica Greeter's Guest Session
.SH SYNOPSIS
.B arctica-greeter-guest-account-script
[
.I OPTIONS
]
.SH DESCRIPTION
\fBWARNING:\fR Never run this script standalone. It is part of the
internal plumbing of Arctica Greeter's guest session feature.
.PP
.SH SEE ALSO
.B arctica-greeter(1)
