.TH ARCTICA-GREETER 1 "Mar 2025" "Version 0.99.8.6" "LightDM Greeter"
.SH NAME
arctica-greeter-magnifier \- Magnifying glass for Arctica Greeter
.SH SYNOPSIS
.B arctica-greeter-magnifier

.SH DESCRIPTION
.B Arctica Greeter
is a LightDM greeter for the modern desktop. It is run by the LightDM
daemon if configured in lightdm.conf.
.PP

.B arctica-greeter-magnifier
is a helper window that can be anabled via the a11y indicator. It
shows a magnified view of the screen portion below the mouse pointer.
.PP

.SH SEE ALSO
.B arctica-greeter
