.TH ARCTICA-GREETER 1 "Jun 2024" "Version 0.99.8.1" "LightDM Greeter"
.SH NAME
arctica-greeter-set-keyboard-layout \- Tool to set the keyboard layout in Arctica Greeter
.SH SYNOPSIS
.B arctica-greeter-set-keyboard-layout

.SH DESCRIPTION
.B Arctica Greeter
is a LightDM greeter for the modern desktop. It is run by the LightDM
daemon if configured in lightdm.conf.
.PP

.B arctica-greeter-set-keyboard-layout
is a helper script for arctica-greeter to set the X11 keyboard layout in
Arctica Greeter. It parses the settings in /etc/default/keyboard and
applies them to the greeter's X11 session.
.PP

.SH SEE ALSO
.B arctica-greeter
