.TH ARCTICA-GREETER 1 "Dec 2023" "Version 0.99.4.6" "LightDM Greeter"
.SH NAME
arctica-greeter \- LightDM greeter for the modern desktop
.SH SYNOPSIS
.B arctica-greeter
[
.I OPTIONS
]
.SH DESCRIPTION
.B Arctica Greeter
is a LightDM greeter for the modern desktop.
.PP
It is run by the LightDM daemon if configured in lightdm.conf.
.PP
It is not normally run by a user, but can run in a test mode with the
\-\-test-mode option. This allows the interface to be tested without
installing an updated version.
.PP
.SH OPTIONS
.TP
.B \-v, \-\-version
Show release version.
.TP
.B \-\-test-mode
Run the greeter in a test mode inside the current X session.
.TP
.B \-\-test\-highcontrast
When in test mode run with a11y highcontrast mode enabled.
.TP
.B \-?, \-\-help
Show help options.
.SH SEE ALSO
.B lightdm
